server:
  port: 8761

spring:
  application:
    name: SpringCloud-Eureka-Server

eureka:
  instance:
    # 自动获取IP
    prefer-ip-address: true
    # 自定义 ip
    # ip-address: 192.168.1.11
  client:
    # 注册自身到eureka服务器
    register-with-eureka: false
    # 表示是否从eureka服务器获取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    # 关闭自我保护模式
    enable-self-preservation: false